apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aws9a-pvc
  namespace: aws9a
spec: 
  storageClassName: aws9a-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
